### ISSUE TITLE
AWS Parameter Store Component

### ISSUE THREAD

**Issue by laardee** [serverless-components/aws-parameter-store#1]
Create a parameter store that allows synchronizing multiple SSM parameters and Secrets Manager secrets to AWS.

The declarative syntax is going to be something like this

```yaml
myParameterStore:
  component: '@serverless/aws-parameter-store'
  inputs:
    parameters:
      - name: /my/parameter/name
        value: '000000'
        type: AWS/SSM/SecureString # something like this
      - name: parameter-name
        value: just-a-string
        type: AWS/SSM/String  # something like this
      - name: pg_password
        value: 'secret'
        type: AWS/SecretsManager  # something like this
        # + whatever parameters are needed, KMS id etc.
```

The component will output the ARN and version (SSM) for each of the parameters.

I'll refine the specification while implementing and open the PR later.
