### ISSUE TITLE
Removing an aws-parameter-store results in timeout error and component not removed

### ISSUE THREAD

**Issue by garethmcc** [serverless-components/aws-parameter-store#7]
Used the following serverless.yml and successfully deployed:

```yml
component: aws-parameter-store
name: parameters
org: garethmccumskey
app: test-parameters
stage: dev

inputs:
```

Once deployed running remove caused a timeout error:

```
test-parameters-store sls remove

serverless ⚡framework
Action: "remove" - Stage: "dev" - Org: "garethmccumskey" - App: "test-parameters" - Name: "parameters"

60s › Serverless › Request timed out after 60 seconds 

  Documentation: https://github.com/serverless/components 
  Support: https://app.serverless.com/support 
  Slack: https://www.serverless.com/slack/ 
```

The state of the deployed component is also in removing state:

![image](https://user-images.githubusercontent.com/4112280/96687007-95cdd100-137f-11eb-8e47-aa1a24c3cc63.png)
